// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/atlas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/atlas">> = Specific
  const handler = {} as typeof import("../../app/atlas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab">> = Specific
  const handler = {} as typeof import("../../app/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules">> = Specific
  const handler = {} as typeof import("../../app/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/quant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quant">> = Specific
  const handler = {} as typeof import("../../app/quant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/atlas/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/atlas/signals">> = Specific
  const handler = {} as typeof import("../../app/api/atlas/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/data-hub/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-hub">> = Specific
  const handler = {} as typeof import("../../app/api/data-hub/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/bars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/bars">> = Specific
  const handler = {} as typeof import("../../app/api/live/bars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/breadth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/breadth">> = Specific
  const handler = {} as typeof import("../../app/api/live/breadth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/instruments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/instruments">> = Specific
  const handler = {} as typeof import("../../app/api/live/instruments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/movers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/movers">> = Specific
  const handler = {} as typeof import("../../app/api/live/movers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/quotes">> = Specific
  const handler = {} as typeof import("../../app/api/live/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live/sectors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/sectors">> = Specific
  const handler = {} as typeof import("../../app/api/live/sectors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/markets">> = Specific
  const handler = {} as typeof import("../../app/api/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/flow">> = Specific
  const handler = {} as typeof import("../../app/api/notes/flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/portfolio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolio">> = Specific
  const handler = {} as typeof import("../../app/api/portfolio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sim/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sim/orders">> = Specific
  const handler = {} as typeof import("../../app/api/sim/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/strategies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/strategies">> = Specific
  const handler = {} as typeof import("../../app/api/strategies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
